name: Deploy SIGAPPA to Production

on:
  push:
    branches: [ finalisasi ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 103.175.204.247
          username: devel
          password: ${{ secrets.VPS_PASSWORD }}
          port: 2244
          script: |
            cd /var/www/html/sigappa
            git pull origin finalisasi

            # Optimasi Laravel
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Reset Permissions
            chmod -R 775 storage bootstrap/cache

            echo "Deployment Berhasil! 🚀"
